CREATE DATABASE IF NOT EXISTS gs_rdbms;
USE gs_rdbms; 
CREATE TABLE IF NOT EXISTS gs_details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);